# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 04:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_pay_bill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pay_Bill',
            new_name='Pay',
        ),
    ]
